version: '3'

services:

  api-db:
    image: mysql:5.7.42
    container_name: api-db
    restart: unless-stopped
    networks:
      back-tier:
        ipv4_address: 172.28.1.1
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret 
      MYSQL_DATABASE: travel_plan
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "172.28.1.1"]
        timeout: 20s
        retries: 10
    volumes:
      - /var/lib/mysql
      - ./dump:/docker-entrypoint-initdb.d
     

  api:
    build: .    
    container_name: api
    restart: unless-stopped
    networks:
      back-tier:
        ipv4_address: 172.28.1.2
    ports:
      - 3000:3000
    depends_on: 
      api-db:
        condition: service_healthy

networks:
  back-tier:    
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16